require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 30 

Metrics/MethodLength:
  Max: 25

Lint/EmptyConditionalBody:
  Enabled: false

CyclomaticComplexity:
  Max: 15

PerceivedComplexity:
  Max: 20

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
  NewCops: enable

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/Rails/InferredSpecType:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false
