version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1
  browser-tools: circleci/browser-tools@1.4.8

services:
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.6
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
  
  rubocop:
    docker:
      - image: cimg/ruby:3.0.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run RuboCop
          command: bundle exec rubocop

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - rubocop
