version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1
  browser-tools: circleci/browser-tools@x.y

services:
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.6
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
  
  rubocop:
    docker:
      - image: cimg/ruby:3.0.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run RuboCop
          command: bundle exec rubocop

  rspec:
  docker:
    - image: cimg/ruby:3.0.6-node
      environment:
        RAILS_ENV: 'test'
        SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    - image: circleci/mysql:8.0
      name: "db"
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password

  steps:
    - checkout
    - browser-tools/install-chrome
    - browser-tools/install-chromedriver
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

    - run:
        name: Check install
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle
          google-chrome --version
          chromedriver --version
    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    - run: bundle exec rake db:create
    - run: bundle exec rake db:schema:load
    - run:
        name: yarn Install
        command: yarn install
    - run: bundle exec bin/webpack
    - run:
        name: Run RSpec
        command: bundle exec rspec

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - rubocop
      - rspec
