default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  port: 3306
  username: root
  password: password
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  socket: /tmp/mysql.sock
  database: <%= ENV['MYSQL_DATABASE'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] %>

test:
  <<: *default
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>
  host: 'localhost’
  database: <%= ENV['MYSQL_DATABASE'] %>
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL']&.sub('mysql://', 'mysql2://') %>
