test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  port: 3306
  username: root
  password: password
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  socket: /tmp/mysql.sock
  database: <%= ENV['MYSQL_DATABASE'] %>
