default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  username: <%= ENV['MYSQL_USERNAME'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'sauna-app' %>

test:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'sauna-app' %>

production:
  <<: *default
  url: <%= ENV['JAWSDB_URL']&.sub('mysql://', 'mysql2://') %>
